# -*- coding: utf-8 -*-
"""Super_Resolution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19k4GbaJ1YBwcvX-8xUnPulAd_ap6vJru
"""

from google.colab import drive
drive.mount('/content/drive')

import cv2
from cv2 import dnn_superres

sr = dnn_superres.DnnSuperResImpl_create()

#read model
path = '/content/drive/My Drive/LapSRN_x8.pb'
sr.readModel(path)

sr.setModel('lapsrn',8)

sr.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
sr.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)

image = cv2.imread('test.png')

result = sr.upsample(image)
cv2.imwrite('result.png',result)